package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/choria-io/discovery_proxy/models"
)

// GetBackupOKCode is the HTTP code returned for type GetBackupOK
const GetBackupOKCode int = 200

/*GetBackupOK Basic successful request

swagger:response getBackupOK
*/
type GetBackupOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessModel `json:"body,omitempty"`
}

// NewGetBackupOK creates GetBackupOK with default headers values
func NewGetBackupOK() *GetBackupOK {
	return &GetBackupOK{}
}

// WithPayload adds the payload to the get backup o k response
func (o *GetBackupOK) WithPayload(payload *models.SuccessModel) *GetBackupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backup o k response
func (o *GetBackupOK) SetPayload(payload *models.SuccessModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBackupInternalServerErrorCode is the HTTP code returned for type GetBackupInternalServerError
const GetBackupInternalServerErrorCode int = 500

/*GetBackupInternalServerError Standard Error Format

swagger:response getBackupInternalServerError
*/
type GetBackupInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewGetBackupInternalServerError creates GetBackupInternalServerError with default headers values
func NewGetBackupInternalServerError() *GetBackupInternalServerError {
	return &GetBackupInternalServerError{}
}

// WithPayload adds the payload to the get backup internal server error response
func (o *GetBackupInternalServerError) WithPayload(payload *models.ErrorModel) *GetBackupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get backup internal server error response
func (o *GetBackupInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBackupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
