package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/choria-io/pdbproxy/models"
)

// GetSetsOKCode is the HTTP code returned for type GetSetsOK
const GetSetsOKCode int = 200

/*GetSetsOK Known Sets

swagger:response getSetsOK
*/
type GetSetsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Sets `json:"body,omitempty"`
}

// NewGetSetsOK creates GetSetsOK with default headers values
func NewGetSetsOK() *GetSetsOK {
	return &GetSetsOK{}
}

// WithPayload adds the payload to the get sets o k response
func (o *GetSetsOK) WithPayload(payload *models.Sets) *GetSetsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sets o k response
func (o *GetSetsOK) SetPayload(payload *models.Sets) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSetsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
