// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSetsHandlerFunc turns a function with the right signature into a get sets handler
type GetSetsHandlerFunc func(GetSetsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSetsHandlerFunc) Handle(params GetSetsParams) middleware.Responder {
	return fn(params)
}

// GetSetsHandler interface for that can handle valid get sets params
type GetSetsHandler interface {
	Handle(GetSetsParams) middleware.Responder
}

// NewGetSets creates a new http.Handler for the get sets operation
func NewGetSets(ctx *middleware.Context, handler GetSetsHandler) *GetSets {
	return &GetSets{Context: ctx, Handler: handler}
}

/*GetSets swagger:route GET /sets getSets

Retrieve list of known sets

*/
type GetSets struct {
	Context *middleware.Context
	Handler GetSetsHandler
}

func (o *GetSets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSetsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
