package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/choria-io/discovery_proxy/models"
)

// NewGetDiscoverParams creates a new GetDiscoverParams object
// with the default values initialized.
func NewGetDiscoverParams() GetDiscoverParams {
	var ()
	return GetDiscoverParams{}
}

// GetDiscoverParams contains all the bound params for the get discover operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetDiscover
type GetDiscoverParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Filter description
	  Required: true
	  In: body
	*/
	Request *models.DiscoveryRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetDiscoverParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.DiscoveryRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("request", "body"))
			} else {
				res = append(res, errors.NewParseError("request", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Request = &body
			}
		}

	} else {
		res = append(res, errors.Required("request", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
