package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/choria-io/discovery_proxy/models"
)

// GetSetSetOKCode is the HTTP code returned for type GetSetSetOK
const GetSetSetOKCode int = 200

/*GetSetSetOK Node Set

swagger:response getSetSetOK
*/
type GetSetSetOK struct {

	/*
	  In: Body
	*/
	Payload *models.Set `json:"body,omitempty"`
}

// NewGetSetSetOK creates GetSetSetOK with default headers values
func NewGetSetSetOK() *GetSetSetOK {
	return &GetSetSetOK{}
}

// WithPayload adds the payload to the get set set o k response
func (o *GetSetSetOK) WithPayload(payload *models.Set) *GetSetSetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get set set o k response
func (o *GetSetSetOK) SetPayload(payload *models.Set) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSetSetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSetSetNotFoundCode is the HTTP code returned for type GetSetSetNotFound
const GetSetSetNotFoundCode int = 404

/*GetSetSetNotFound Not found

swagger:response getSetSetNotFound
*/
type GetSetSetNotFound struct {
}

// NewGetSetSetNotFound creates GetSetSetNotFound with default headers values
func NewGetSetSetNotFound() *GetSetSetNotFound {
	return &GetSetSetNotFound{}
}

// WriteResponse to the client
func (o *GetSetSetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// GetSetSetInternalServerErrorCode is the HTTP code returned for type GetSetSetInternalServerError
const GetSetSetInternalServerErrorCode int = 500

/*GetSetSetInternalServerError Standard Error Format

swagger:response getSetSetInternalServerError
*/
type GetSetSetInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewGetSetSetInternalServerError creates GetSetSetInternalServerError with default headers values
func NewGetSetSetInternalServerError() *GetSetSetInternalServerError {
	return &GetSetSetInternalServerError{}
}

// WithPayload adds the payload to the get set set internal server error response
func (o *GetSetSetInternalServerError) WithPayload(payload *models.ErrorModel) *GetSetSetInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get set set internal server error response
func (o *GetSetSetInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSetSetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
