package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPdbproxyAPI creates a new Pdbproxy instance
func NewPdbproxyAPI(spec *loads.Document) *PdbproxyAPI {
	return &PdbproxyAPI{
		handlers:        make(map[string]map[string]http.Handler),
		formats:         strfmt.Default,
		defaultConsumes: "application/json",
		defaultProduces: "application/json",
		ServerShutdown:  func() {},
		spec:            spec,
		ServeError:      errors.ServeError,
		JSONConsumer:    runtime.JSONConsumer(),
		JSONProducer:    runtime.JSONProducer(),
		BinProducer:     runtime.ByteStreamProducer(),
		DeleteSetSetHandler: DeleteSetSetHandlerFunc(func(params DeleteSetSetParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteSetSet has not yet been implemented")
		}),
		GetBackupHandler: GetBackupHandlerFunc(func(params GetBackupParams) middleware.Responder {
			return middleware.NotImplemented("operation GetBackup has not yet been implemented")
		}),
		GetDiscoverHandler: GetDiscoverHandlerFunc(func(params GetDiscoverParams) middleware.Responder {
			return middleware.NotImplemented("operation GetDiscover has not yet been implemented")
		}),
		GetSetSetHandler: GetSetSetHandlerFunc(func(params GetSetSetParams) middleware.Responder {
			return middleware.NotImplemented("operation GetSetSet has not yet been implemented")
		}),
		GetSetsHandler: GetSetsHandlerFunc(func(params GetSetsParams) middleware.Responder {
			return middleware.NotImplemented("operation GetSets has not yet been implemented")
		}),
		PostSetHandler: PostSetHandlerFunc(func(params PostSetParams) middleware.Responder {
			return middleware.NotImplemented("operation PostSet has not yet been implemented")
		}),
		PutSetSetHandler: PutSetSetHandlerFunc(func(params PutSetSetParams) middleware.Responder {
			return middleware.NotImplemented("operation PutSetSet has not yet been implemented")
		}),
	}
}

/*PdbproxyAPI API to do Choria Discovery via REST services */
type PdbproxyAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer
	// BinProducer registers a producer for a "application/octet-stream" mime type
	BinProducer runtime.Producer

	// DeleteSetSetHandler sets the operation handler for the delete set set operation
	DeleteSetSetHandler DeleteSetSetHandler
	// GetBackupHandler sets the operation handler for the get backup operation
	GetBackupHandler GetBackupHandler
	// GetDiscoverHandler sets the operation handler for the get discover operation
	GetDiscoverHandler GetDiscoverHandler
	// GetSetSetHandler sets the operation handler for the get set set operation
	GetSetSetHandler GetSetSetHandler
	// GetSetsHandler sets the operation handler for the get sets operation
	GetSetsHandler GetSetsHandler
	// PostSetHandler sets the operation handler for the post set operation
	PostSetHandler PostSetHandler
	// PutSetSetHandler sets the operation handler for the put set set operation
	PutSetSetHandler PutSetSetHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *PdbproxyAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *PdbproxyAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *PdbproxyAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *PdbproxyAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *PdbproxyAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *PdbproxyAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *PdbproxyAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the PdbproxyAPI
func (o *PdbproxyAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BinProducer == nil {
		unregistered = append(unregistered, "BinProducer")
	}

	if o.DeleteSetSetHandler == nil {
		unregistered = append(unregistered, "DeleteSetSetHandler")
	}

	if o.GetBackupHandler == nil {
		unregistered = append(unregistered, "GetBackupHandler")
	}

	if o.GetDiscoverHandler == nil {
		unregistered = append(unregistered, "GetDiscoverHandler")
	}

	if o.GetSetSetHandler == nil {
		unregistered = append(unregistered, "GetSetSetHandler")
	}

	if o.GetSetsHandler == nil {
		unregistered = append(unregistered, "GetSetsHandler")
	}

	if o.PostSetHandler == nil {
		unregistered = append(unregistered, "PostSetHandler")
	}

	if o.PutSetSetHandler == nil {
		unregistered = append(unregistered, "PutSetSetHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *PdbproxyAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *PdbproxyAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *PdbproxyAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *PdbproxyAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		case "application/octet-stream":
			result["application/octet-stream"] = o.BinProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *PdbproxyAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the pdbproxy API
func (o *PdbproxyAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *PdbproxyAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/set/{set}"] = NewDeleteSetSet(o.context, o.DeleteSetSetHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/backup"] = NewGetBackup(o.context, o.GetBackupHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/discover"] = NewGetDiscover(o.context, o.GetDiscoverHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/set/{set}"] = NewGetSetSet(o.context, o.GetSetSetHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/sets"] = NewGetSets(o.context, o.GetSetsHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/set"] = NewPostSet(o.context, o.PostSetHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/set/{set}"] = NewPutSetSet(o.context, o.PutSetSetHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *PdbproxyAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middelware as you see fit
func (o *PdbproxyAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}
