// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/choria-io/discovery_proxy/models"
)

// PutSetSetOKCode is the HTTP code returned for type PutSetSetOK
const PutSetSetOKCode int = 200

/*PutSetSetOK Basic successful request

swagger:response putSetSetOK
*/
type PutSetSetOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessModel `json:"body,omitempty"`
}

// NewPutSetSetOK creates PutSetSetOK with default headers values
func NewPutSetSetOK() *PutSetSetOK {
	return &PutSetSetOK{}
}

// WithPayload adds the payload to the put set set o k response
func (o *PutSetSetOK) WithPayload(payload *models.SuccessModel) *PutSetSetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put set set o k response
func (o *PutSetSetOK) SetPayload(payload *models.SuccessModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutSetSetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutSetSetNotFoundCode is the HTTP code returned for type PutSetSetNotFound
const PutSetSetNotFoundCode int = 404

/*PutSetSetNotFound Not found

swagger:response putSetSetNotFound
*/
type PutSetSetNotFound struct {
}

// NewPutSetSetNotFound creates PutSetSetNotFound with default headers values
func NewPutSetSetNotFound() *PutSetSetNotFound {
	return &PutSetSetNotFound{}
}

// WriteResponse to the client
func (o *PutSetSetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// PutSetSetInternalServerErrorCode is the HTTP code returned for type PutSetSetInternalServerError
const PutSetSetInternalServerErrorCode int = 500

/*PutSetSetInternalServerError Standard Error Format

swagger:response putSetSetInternalServerError
*/
type PutSetSetInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewPutSetSetInternalServerError creates PutSetSetInternalServerError with default headers values
func NewPutSetSetInternalServerError() *PutSetSetInternalServerError {
	return &PutSetSetInternalServerError{}
}

// WithPayload adds the payload to the put set set internal server error response
func (o *PutSetSetInternalServerError) WithPayload(payload *models.ErrorModel) *PutSetSetInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put set set internal server error response
func (o *PutSetSetInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutSetSetInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
