package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/choria-io/discovery_proxy/models"
)

// NewPutSetSetParams creates a new PutSetSetParams object
// with the default values initialized.
func NewPutSetSetParams() PutSetSetParams {
	var ()
	return PutSetSetParams{}
}

// PutSetSetParams contains all the bound params for the put set set operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutSetSet
type PutSetSetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Set Properties
	  Required: true
	  In: body
	*/
	NewSet *models.Set
	/*Node set to retrieve
	  Required: true
	  In: path
	*/
	Set string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PutSetSetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Set
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("newSet", "body"))
			} else {
				res = append(res, errors.NewParseError("newSet", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.NewSet = &body
			}
		}

	} else {
		res = append(res, errors.Required("newSet", "body"))
	}

	rSet, rhkSet, _ := route.Params.GetOK("set")
	if err := o.bindSet(rSet, rhkSet, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutSetSetParams) bindSet(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Set = raw

	return nil
}
