// Code generated by go-swagger; DO NOT EDIT.

/*Package restapi Choria Discovery API

API to do Choria Discovery via REST services


    Schemes:
      https
    Host: localhost
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json


    Produces:
    - application/json

    - application/octet-stream


swagger:meta
*/
package restapi
