package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSetSetParams creates a new DeleteSetSetParams object
// with the default values initialized.
func NewDeleteSetSetParams() *DeleteSetSetParams {
	var ()
	return &DeleteSetSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSetSetParamsWithTimeout creates a new DeleteSetSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSetSetParamsWithTimeout(timeout time.Duration) *DeleteSetSetParams {
	var ()
	return &DeleteSetSetParams{

		timeout: timeout,
	}
}

// NewDeleteSetSetParamsWithContext creates a new DeleteSetSetParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSetSetParamsWithContext(ctx context.Context) *DeleteSetSetParams {
	var ()
	return &DeleteSetSetParams{

		Context: ctx,
	}
}

// NewDeleteSetSetParamsWithHTTPClient creates a new DeleteSetSetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSetSetParamsWithHTTPClient(client *http.Client) *DeleteSetSetParams {
	var ()
	return &DeleteSetSetParams{
		HTTPClient: client,
	}
}

/*DeleteSetSetParams contains all the parameters to send to the API endpoint
for the delete set set operation typically these are written to a http.Request
*/
type DeleteSetSetParams struct {

	/*Set
	  Node set to delete

	*/
	Set string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete set set params
func (o *DeleteSetSetParams) WithTimeout(timeout time.Duration) *DeleteSetSetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete set set params
func (o *DeleteSetSetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete set set params
func (o *DeleteSetSetParams) WithContext(ctx context.Context) *DeleteSetSetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete set set params
func (o *DeleteSetSetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete set set params
func (o *DeleteSetSetParams) WithHTTPClient(client *http.Client) *DeleteSetSetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete set set params
func (o *DeleteSetSetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSet adds the set to the delete set set params
func (o *DeleteSetSetParams) WithSet(set string) *DeleteSetSetParams {
	o.SetSet(set)
	return o
}

// SetSet adds the set to the delete set set params
func (o *DeleteSetSetParams) SetSet(set string) {
	o.Set = set
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSetSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param set
	if err := r.SetPathParam("set", o.Set); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
