package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/choria-io/pdbproxy/models"
)

// DeleteSetSetReader is a Reader for the DeleteSetSet structure.
type DeleteSetSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSetSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteSetSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteSetSetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteSetSetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSetSetOK creates a DeleteSetSetOK with default headers values
func NewDeleteSetSetOK() *DeleteSetSetOK {
	return &DeleteSetSetOK{}
}

/*DeleteSetSetOK handles this case with default header values.

Basic successful request
*/
type DeleteSetSetOK struct {
	Payload *models.SuccessModel
}

func (o *DeleteSetSetOK) Error() string {
	return fmt.Sprintf("[DELETE /set/{set}][%d] deleteSetSetOK  %+v", 200, o.Payload)
}

func (o *DeleteSetSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSetSetNotFound creates a DeleteSetSetNotFound with default headers values
func NewDeleteSetSetNotFound() *DeleteSetSetNotFound {
	return &DeleteSetSetNotFound{}
}

/*DeleteSetSetNotFound handles this case with default header values.

Not found
*/
type DeleteSetSetNotFound struct {
}

func (o *DeleteSetSetNotFound) Error() string {
	return fmt.Sprintf("[DELETE /set/{set}][%d] deleteSetSetNotFound ", 404)
}

func (o *DeleteSetSetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSetSetInternalServerError creates a DeleteSetSetInternalServerError with default headers values
func NewDeleteSetSetInternalServerError() *DeleteSetSetInternalServerError {
	return &DeleteSetSetInternalServerError{}
}

/*DeleteSetSetInternalServerError handles this case with default header values.

Standard Error Format
*/
type DeleteSetSetInternalServerError struct {
	Payload *models.ErrorModel
}

func (o *DeleteSetSetInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /set/{set}][%d] deleteSetSetInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteSetSetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
