package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSetsParams creates a new GetSetsParams object
// with the default values initialized.
func NewGetSetsParams() *GetSetsParams {

	return &GetSetsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSetsParamsWithTimeout creates a new GetSetsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSetsParamsWithTimeout(timeout time.Duration) *GetSetsParams {

	return &GetSetsParams{

		timeout: timeout,
	}
}

// NewGetSetsParamsWithContext creates a new GetSetsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSetsParamsWithContext(ctx context.Context) *GetSetsParams {

	return &GetSetsParams{

		Context: ctx,
	}
}

// NewGetSetsParamsWithHTTPClient creates a new GetSetsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSetsParamsWithHTTPClient(client *http.Client) *GetSetsParams {

	return &GetSetsParams{
		HTTPClient: client,
	}
}

/*GetSetsParams contains all the parameters to send to the API endpoint
for the get sets operation typically these are written to a http.Request
*/
type GetSetsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get sets params
func (o *GetSetsParams) WithTimeout(timeout time.Duration) *GetSetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sets params
func (o *GetSetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sets params
func (o *GetSetsParams) WithContext(ctx context.Context) *GetSetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sets params
func (o *GetSetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sets params
func (o *GetSetsParams) WithHTTPClient(client *http.Client) *GetSetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sets params
func (o *GetSetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
