package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/choria-io/discovery_proxy/models"
)

// GetSetSetReader is a Reader for the GetSetSet structure.
type GetSetSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSetSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSetSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetSetSetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetSetSetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSetSetOK creates a GetSetSetOK with default headers values
func NewGetSetSetOK() *GetSetSetOK {
	return &GetSetSetOK{}
}

/*GetSetSetOK handles this case with default header values.

Node Set
*/
type GetSetSetOK struct {
	Payload *models.Set
}

func (o *GetSetSetOK) Error() string {
	return fmt.Sprintf("[GET /set/{set}][%d] getSetSetOK  %+v", 200, o.Payload)
}

func (o *GetSetSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Set)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSetSetNotFound creates a GetSetSetNotFound with default headers values
func NewGetSetSetNotFound() *GetSetSetNotFound {
	return &GetSetSetNotFound{}
}

/*GetSetSetNotFound handles this case with default header values.

Not found
*/
type GetSetSetNotFound struct {
}

func (o *GetSetSetNotFound) Error() string {
	return fmt.Sprintf("[GET /set/{set}][%d] getSetSetNotFound ", 404)
}

func (o *GetSetSetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSetSetInternalServerError creates a GetSetSetInternalServerError with default headers values
func NewGetSetSetInternalServerError() *GetSetSetInternalServerError {
	return &GetSetSetInternalServerError{}
}

/*GetSetSetInternalServerError handles this case with default header values.

Standard Error Format
*/
type GetSetSetInternalServerError struct {
	Payload *models.ErrorModel
}

func (o *GetSetSetInternalServerError) Error() string {
	return fmt.Sprintf("[GET /set/{set}][%d] getSetSetInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSetSetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
