package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBackupParams creates a new GetBackupParams object
// with the default values initialized.
func NewGetBackupParams() *GetBackupParams {

	return &GetBackupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBackupParamsWithTimeout creates a new GetBackupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBackupParamsWithTimeout(timeout time.Duration) *GetBackupParams {

	return &GetBackupParams{

		timeout: timeout,
	}
}

// NewGetBackupParamsWithContext creates a new GetBackupParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBackupParamsWithContext(ctx context.Context) *GetBackupParams {

	return &GetBackupParams{

		Context: ctx,
	}
}

// NewGetBackupParamsWithHTTPClient creates a new GetBackupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBackupParamsWithHTTPClient(client *http.Client) *GetBackupParams {

	return &GetBackupParams{
		HTTPClient: client,
	}
}

/*GetBackupParams contains all the parameters to send to the API endpoint
for the get backup operation typically these are written to a http.Request
*/
type GetBackupParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get backup params
func (o *GetBackupParams) WithTimeout(timeout time.Duration) *GetBackupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get backup params
func (o *GetBackupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get backup params
func (o *GetBackupParams) WithContext(ctx context.Context) *GetBackupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get backup params
func (o *GetBackupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get backup params
func (o *GetBackupParams) WithHTTPClient(client *http.Client) *GetBackupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get backup params
func (o *GetBackupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetBackupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
