package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/choria-io/pdbproxy/models"
)

// NewPostSetParams creates a new PostSetParams object
// with the default values initialized.
func NewPostSetParams() *PostSetParams {
	var ()
	return &PostSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSetParamsWithTimeout creates a new PostSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSetParamsWithTimeout(timeout time.Duration) *PostSetParams {
	var ()
	return &PostSetParams{

		timeout: timeout,
	}
}

// NewPostSetParamsWithContext creates a new PostSetParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSetParamsWithContext(ctx context.Context) *PostSetParams {
	var ()
	return &PostSetParams{

		Context: ctx,
	}
}

// NewPostSetParamsWithHTTPClient creates a new PostSetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSetParamsWithHTTPClient(client *http.Client) *PostSetParams {
	var ()
	return &PostSetParams{
		HTTPClient: client,
	}
}

/*PostSetParams contains all the parameters to send to the API endpoint
for the post set operation typically these are written to a http.Request
*/
type PostSetParams struct {

	/*Set
	  Node set to store

	*/
	Set *models.Set

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post set params
func (o *PostSetParams) WithTimeout(timeout time.Duration) *PostSetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post set params
func (o *PostSetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post set params
func (o *PostSetParams) WithContext(ctx context.Context) *PostSetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post set params
func (o *PostSetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post set params
func (o *PostSetParams) WithHTTPClient(client *http.Client) *PostSetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post set params
func (o *PostSetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSet adds the set to the post set params
func (o *PostSetParams) WithSet(set *models.Set) *PostSetParams {
	o.SetSet(set)
	return o
}

// SetSet adds the set to the post set params
func (o *PostSetParams) SetSet(set *models.Set) {
	o.Set = set
}

// WriteToRequest writes these params to a swagger request
func (o *PostSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Set == nil {
		o.Set = new(models.Set)
	}

	if err := r.SetBodyParam(o.Set); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
