package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DiscoverySuccessModel discovery success model
// swagger:model discoverySuccessModel
type DiscoverySuccessModel struct {

	// nodes
	Nodes []string `json:"nodes"`

	// HTTP Status Code
	Status int64 `json:"status,omitempty"`
}

// Validate validates this discovery success model
func (m *DiscoverySuccessModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNodes(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DiscoverySuccessModel) validateNodes(formats strfmt.Registry) error {

	if swag.IsZero(m.Nodes) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DiscoverySuccessModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DiscoverySuccessModel) UnmarshalBinary(b []byte) error {
	var res DiscoverySuccessModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
